[book]
authors = ["Oliver Nordbjerg"]
language = "en"
multilingual = false
src = "src"
title = "The Foundry Book"

[output.html]
git-repository-url = "https://github.com/onbjerg/foundry-book"
edit-url-template = "https://github.com/onbjerg/foundry-book/edit/master/src/doc/{path}"
default-theme = "ayu"
additional-js = ["src/static/solidity.min.js"]
